[phases.setup]
aptPkgs = [
    '...',
    'fonts-liberation',
    'libappindicator3-1',
    'libasound2',
    'libatk-bridge2.0-0',
    'libatk1.0-0',
    'libgbm1',
    'libgtk-3-0',
    'libnspr4',
    'libnss3',
    'libx11-xcb1',
    'libxcomposite1',
    'libxcursor1',
    'libxdamage1',
    'libxfixes3',
    'libxi6',
    'libxrandr2',
    'libxss1',
    'libxtst6',
    'xdg-utils',
    'libdrm-amdgpu1',
    'libdrm-nouveau2',
    'libdrm-radeon1',
    'libedit2',
    'libelf1',
    'libfontenc1',
    'libgl1',
    'libgl1-mesa-dri',
    'libglapi-mesa',
    'libglvnd0',
    'libglx-mesa0',
    'libglx0',
    'libice6',
    'libllvm15',
    'libsensors-config',
    'libsensors5',
    'libsm6',
    'libunwind8',
    'libxaw7',
    'libxcb-dri2-0',
    'libxcb-dri3-0',
    'libxcb-glx0',
    'libxcb-present0',
    'libxcb-sync1',
    'libxcb-xfixes0',
    'libxfont2',
    'libxkbfile1',
    'libxmu6',
    'libxmuu1',
    'libxpm4',
    'libxshmfence1',
    'libxt6',
    'libxxf86vm1',
    'x11-xkb-utils',
    'xauth',
    'xfonts-encodings',
    'xfonts-utils',
    'xserver-common'
]